name: Daily Weather Data Automation

on:
  schedule:
    - cron: '0 10 * * *'  # Run daily at 10:00 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Run the weather.sh script
      - name: Run Weather Script
        run: |
          chmod +x weather.sh
          ./weather.sh

      # Step 3: Commit and Push Changes
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sarahembarry/computer-infrastructure-assesment.git
          git add data/weather/
          git commit -m "Automated weather data update - $(date)"
          git push
